### ISSUE TITLE
9 custom folders moves your inbox in position

### ISSUE THREAD

**Issue by joris85** [freescout-helpdesk/freescout#1109]
Hi guys,

Always when i reach 9 custom folders my inbox moves down.
https://www.dropbox.com/s/t8izrrl00j23fad/Schermafbeelding%202021-03-25%20om%2009.24.40.png?dl=0

I have mentioned this before and thought you guys would fix it but its still not working as expected :-)
Hope this is just a small fix.
Thanks

**Comment by freescout-helpdesk** [comment]
Can you reproduce the issue on demo.freescout.net?

**Comment by joris85** [comment]
I can't make a custom folder there :-)
https://www.dropbox.com/s/ss3eh5so3kqz8jf/Schermafbeelding%202021-03-25%20om%2009.48.52.png?dl=0

**Comment by freescout-helpdesk** [comment]
Fixed in Custom Folders Module v1.0.3

**Comment by joris85** [comment]
@freescout-helpdesk 
Super happy you guys worked on this.
On one installation it is fixed, awesome.
The other not.

Though on all updates i get an error on this application though untill now it always seemed to be updated.
So i manually updated the custom folders from the other application where it is working.
Still not working.

It is even a much bigger mess :-D

Any thoughts here?
If there is a Freescout professional that can help I am willing to pay to checkout my installation,
I am not asking to help me for free or expect you guys always fix it :-D

<img width="242" alt="Schermafbeelding 2021-03-26 om 10 57 17" src="https://user-images.githubusercontent.com/5088751/112615062-53268e00-8e22-11eb-859c-81b0d7c90a0b.png">

**Comment by freescout-helpdesk** [comment]
One more patch released: Custom Folders Module v1.0.4
