### ISSUE TITLE
Ticket Number Module customize prefix and suffix not working

### ISSUE THREAD

**Issue by jshrek** [freescout-helpdesk/freescout#1929]
On the Ticket Number Module page here https://freescout.net/module/ticket-number/
it says:
```
Customizing
Via the following variables in the .env file ticket number prefix and suffix can be customized:
TICKETNUMBER_PREFIX=”(“
TICKETNUMBER_SUFFIX=”) “
```

The first issue is that if you copy and paste the code into the .env file and clear the cache, it will cause Freescout to crash (stop working) because the code is using ”fancy/curly“ double-quotes instead of "standard" double-quotes. So this code example needs to be fixed.

The second issue is that after adding the prefix and suffix to the .env file with the proper double quotes, and running `php artisan freescout:clear-cache` the prefix and suffix do not take effect.

**Comment by freescout-helpdesk** [comment]
> The first issue is that if you copy and paste the code into the .env file and clear the cache, it will cause Freescout to crash (stop working) because the code is using ”fancy/curly“ double-quotes instead of "standard" double-quotes. So this code example needs to be fixed.

Thanks. It has been fixed.

**Comment by freescout-helpdesk** [comment]
> The second issue is that after adding the prefix and suffix to the .env file with the proper double quotes, and running php artisan freescout:clear-cache the prefix and suffix do not take effect.

This works fine for us and others.

**Comment by jshrek** [comment]
So what I am doing wrong?

I have this in the .env file
![komodo_2022-04-24_08-58-08](https://user-images.githubusercontent.com/19673842/164980087-9c2ff85c-46dd-41e3-b7fa-2a0e2ba996eb.jpg)

and then I run the Clear Cache

and then I get this in my email subject:
![thunderbird_2022-04-24_08-57-57](https://user-images.githubusercontent.com/19673842/164980121-8da4b73d-48bd-42dd-8848-b42b7e190b11.jpg)

**Comment by freescout-helpdesk** [comment]
Make sure the module is Active.
Try to clear the cache from Manage > System > Tools

**Comment by jshrek** [comment]
Yes the module is active (hence the [#84] ticket number showing up in the email subject), I tried clearing the cache from Manage > System > Tools as well, but issue still exists.

I also tried de-activating then re-activating the module, but issue still exists.

Thanks

**Comment by freescout-helpdesk** [comment]
Strange. So the only way in your case would be to make changes directly in /Modules/TicketNumber/Providers/TicketNumberServiceProvider.php on lines 37 and 43

**Comment by jshrek** [comment]
I am re-opening this ticket as I have further updates...

The custom prefix and suffix work fine when I compose a new conversation from within Freescout (clicking the envelope button), but they do not work when an email is auto-fetched to create a new conversation.

Let's say I have this:
TICKETNUMBER_PREFIX="[My Ticket# "
TICKETNUMBER_SUFFIX="]--"

When I choose compose New Conversation, and email it to somebody, the subject is correct, as follows:
[My Ticket#1234]--the subject

But when a new email is fetched and a new conversation is created automatically, the notification email I get has incorrect subject, as follows (it appears to be the default settings without the custom prefix/suffix):
[#1235] the subject

Using version 1.8.50 of FreeScout with version 1.0.2 of Ticket Number module

**Comment by freescout-helpdesk** [comment]
The prefix and suffix are added only to emails sent to customer - they are not visible in the conversation in FreeScout.

**Comment by jshrek** [comment]
I am not looking for them in FreeScout.

When a customer sends a new email, and the email is fetched, FreeScout will automatically create a new conversation. The NOTIFICATION EMAIL that is sent to our staff users about a new conversation being created has a subject that does NOT include the custom prefix and suffix.

Only the email that is sent to customer has the custom prefix and suffix.

Personally I think that ALL subjects, both the customer emails and staff notification emails, should be affected by this custom prefix and suffix. 

Thanks

**Comment by rjmedlin** [comment]
Where is this .env file supposed to live, I've tried in 3 locations.  Inside the docker shell, in the host docker directory, in the module directory.  Yes its enabled, yes I clear the cache but it still does not show in customer email.

**Comment by jshrek** [comment]
.env should just be in the main root folder. 
There should be a .env.sample file already there:

![Image](https://github.com/user-attachments/assets/95a2a4d8-128e-421a-bc04-434e102f58c7)

**Comment by rjmedlin** [comment]
thanks for the fast reply.  I have 1 there 
root@support:/opt/freescout# ls -la
total 32
drwxr-xr-x 5 root root 4096 Feb 26 20:10 .
drwxr-xr-x 7 root root 4096 Feb 26 17:11 ..
-rw-r--r-- 1 root root   61 Feb 26 19:41 .env
drwxr-xr-x 4   80   82 4096 Feb 26 20:55 data
drwxr-xr-x 4   80   82 4096 Feb 26 18:47 data-old
-rw-r--r-- 1 root root  620 Feb 26 20:10 docker-compose.yml
drwxr-xr-x 5 root root 4096 Feb 26 17:13 logs
-rw-r--r-- 1 root root  398 Feb 26 19:05 module-keys.txt

root@support:/opt/freescout# cat .env
TICKETNUMBER_PREFIX="[My Ticket# "
TICKETNUMBER_SUFFIX="]--"

**Comment by rjmedlin** [comment]
ya, I have 1 there as well
root@support:/opt/freescout/data/Modules/TicketNumber# cat .env
TICKETNUMBER_PREFIX="[My Ticket# "
TICKETNUMBER_SUFFIX="]--"

**Comment by rjmedlin** [comment]
I think perhaps the difference in view is that I purchased and installed this via the website rather than a clone of the repo
