### ISSUE TITLE
Bug: Freescout ticket does not realize it has attachments after ticket merge!

### ISSUE THREAD

**Issue by ar-ml** [freescout-helpdesk/freescout#2681]
**Steps to reproduce:**
1. Send an email **without** an attachment to your freescout mailbox
-> New ticket No.1 will be created
2. Send a second email (from the same email address) **with** an attachment (e.g. test.pdf, 1MB) to your freescout postbox
-> Another ticket No.2 will be created. This ticket will have the attachment, and display a paper clip icon in list view.
3. Now open ticket No.1
4. In Ticket No.1 go to three-dots-menu>Merge and merge Ticket No.1 with Ticket No.2
-> The tickets will be merged. The merged ticket will keep Ticket number No.1
5. Now check the conversation record: The attachment will be displayed correctly in the conversation record.
6. Now check the merged ticket in the list view (e.g. in not assigned-list): 
the merged ticket does not display the attachment symbol (paperclip)! So it forgot that it has an attachment. Or, more precise: the Ticket No.1 never realized that it now has an attachment (which was imported from ticket No.2)
7. Now open the ticket and try to forward the ticket to another email adders.
-> the attachments will be missing when composing the email - and of course they will be also missing at the recipient!

**Why this is a problem:**
I need to be able to forward merged tickets including all attachments to someone else! 
It is bad UX if suddenly attachments are missing or the paperclip symbol is not displayed in the list view.

**Tried workaround (not working for me):**
Instead of starting the ticket merge from ticket No.1, I tried starting the ticket merge from ticket No.2 instead. In this case there is no problem with the attachment.
Unfortunately this is **not** a solution for me, because of another UX problem, see my other post:  #2682

**Questions**
Does anyone know a workaround which might work for me?
Can you fix this issue and maybe also the UX issue here:  #2682
Thank you!

(P.S. Freescout is awesome, Thank you for your great work)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch.

**Comment by ar-ml** [comment]
thank you very much! 
I checked for updates on the freescout system status page, but I guess there is no new release.
How can I easily test the changes you've made to the code in my live environment?
Is it safe to test it live?

**Comment by freescout-helpdesk** [comment]
You'll need to know Git: https://github.com/freescout-helpdesk/freescout/wiki/Installation-Guide#if-you-are-planning-to-contribute-to-the-project
You can wait for the next release. Usually they appear almost every week.

**Comment by ar-ml** [comment]
For testing:
Can I just manually copy the php code from the [github page here](https://github.com/freescout-helpdesk/freescout/blob/e17db424603e267834a81695f57a9111c93e5f1b/app/Conversation.php) and paste it into the Conversation.php on my live server? 
Would automatic updates still work then with the next release? Would the manually changed php file still get overwritten with the next release (if there are further changes)?

**Comment by freescout-helpdesk** [comment]
Yes to all.
