### ISSUE TITLE
Fetching error

### ISSUE THREAD

**Issue by sam-suresh** [freescout-helpdesk/freescout#269]
Hi

What might caused this error;

`imap_open(): Couldn't open stream {imap.gmail.com:993/imap/ssl}. Certificate failure for imap.gmail.com: self signed certificate: /OU=No SNI provided; please fix your client./CN=invalid2.invalid; File: /srv/users/helpdesk/apps/helpdesk/vendor/webklex/laravel-imap/src/IMAP/Client.php (230)`

This happened after added second mailbox. Both first and second unable to fetch mails. 
Tried with IMAP and POP. 

And before adding second mailbox, it was working with 2FA turned on and created an app specific password in GSuite. Now with 2FA turned off and allowed less secure app still shows certificate failure. 

Connection test passed! But not fetching new mails. 
<img width="585" alt="Screenshot 2019-06-12 at 3 48 11 PM" src="https://user-images.githubusercontent.com/5198092/59332753-9127f000-8d29-11e9-9b9e-089031c132da.png">

Running in production environment with NGinX and Apache SSL by LetsEncrypt.

**Comment by sam-suresh** [comment]
ok solved by bypassing certificate validation in /vendor/webklex/laravel-imap/src/IMAP/Client.php

Looks like validate-cert is not implemented yet?

**Comment by freescout-helpdesk** [comment]
> ok solved by bypassing certificate validation in /vendor/webklex/laravel-imap/src/IMAP/Client.php
> 
> Looks like validate-cert is not implemented yet?

Not yet. Coming in the next release.

**Comment by C0rn3j** [comment]
`imap_open(): Couldn't open stream {imap.gmail.com:993/imap/ssl}. Certificate failure for imap.gmail.com: self signed certificate: /OU=No SNI provided; please fix your client./CN=invalid2.invalid`

6 days ago we've started getting the above error on 1.1.6, despite the same settings working before.

Updated to 1.1.9 and still getting the same error, unchecking the new Validate Certificate checkbox makes the connection go through but that's just hiding the error, did something change on Google's side?

**Comment by deusnuno** [comment]
Hi!
After the update I've continued to see the same issue. Even after disabling cert verification in the connection settings menu.

The only way it started fetching emails again was to actually comment the lines referred in #253

**Comment by Troca82** [comment]
I can confirm that it is not working for us either. The option simply does not work.
