### ISSUE TITLE
1.8.128 update has broken the ability to read emails from Monday

### ISSUE THREAD

**Issue by dreyerretief** [freescout-helpdesk/freescout#3907]
1.8.128 Update that we installed today has broken emails from monday we cannot see the body on the the ticket view, but it does show on original view..

![image](https://github.com/freescout-helpdesk/freescout/assets/165007167/84528c4e-d06a-4157-bdca-c15c035a5604)

![image](https://github.com/freescout-helpdesk/freescout/assets/165007167/16a93658-1af1-45c5-a242-c037dec79547)

**Comment by freescout-helpdesk** [comment]
This issue was introduced in 1.8.127 release and fixed in 1.8.128.

**Comment by dreyerretief** [comment]
We are on 1.8.128

**Comment by freescout-helpdesk** [comment]
Have you been able to see exactly the same email before?

**Comment by dreyerretief** [comment]
Yes before the update everything was working i was on the previous release...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sogjugz** [comment]
@freescout-helpdesk Hello,

Looks like the issue is still present in the 1.8.130 as you can see below:

![image](https://github.com/freescout-helpdesk/freescout/assets/62724105/3a777d2f-00c7-49e4-aa70-47505b859d31)

Here is the email body:
[EmailBody.txt](https://github.com/freescout-helpdesk/freescout/files/14824765/EmailBody.txt)

**Comment by freescout-helpdesk** [comment]
@sogjugz Your email (https://github.com/freescout-helpdesk/freescout/issues/3907#issuecomment-2029881830) looks like this on the latest FreeScout version and similar on previous FreeScout versions:

![2024-04-01_18-58-31](https://github.com/freescout-helpdesk/freescout/assets/40499291/f807ba47-e463-4f89-854c-926a62572e87)

**Comment by dreyerretief** [comment]
The issue is still happening  the latest version.... Monday replies are unreadable...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by avegalco** [comment]
Hello team.
Same problem here. Only in "view original message" the message displays correctly.

**Comment by avegalco** [comment]
Hello team. 
Is there any update on this? 
The emails are still displaying incorrectly and it's causing disruption to our operations. 
We have version 1.8.130 with 22 additional modules, but none of them seem to be the problem. 
Thank you.

**Comment by freescout-helpdesk** [comment]
@avegalco Try to comment lines 316 and 320 in `/app/Thread.php` and check how it goes:
```
//$body = preg_replace("/(<[^<>\r\n]+class=([\"'][^\"']* |[\"']))(collapse|hidden)([\"' ])/", '$1$4', $body) ?: $body;

//$body = preg_replace('/<!\-\-\[if [^>]+\]><!\-\->(.*?)<![ ]+\-\-<!\[endif\]\-\->/s', '$1', $body);
```

**Comment by freescout-helpdesk** [comment]
It means the issue is not in this or that release. HTML Purifuer library simply can not parse HTML of your email.

**Comment by avegalco** [comment]
Hello team. 
I have the feeling that this issue is being underestimated. 
FreeScout is not displaying messages from many clients and suppliers correctly, it's not just a specific template or an isolated issue. 
If, as mentioned before, this is a problem related to a library, I would appreciate it if you could please inform me how to solve it, as so far, updates fixing errors had been the only necessary action in similar cases. 
Just to confirm, the problem started when we updated to 1.8.130 and it persists in 1.8.131.
Thank you very much.

**Comment by freescout-helpdesk** [comment]
Try to update to the previous FreeScout version using manual [updating method](https://github.com/freescout-helpdesk/freescout/wiki/Updating-FreeScout) and check how it goes: https://github.com/freescout-helpdesk/freescout/releases

**Comment by sogjugz** [comment]
Hi @freescout-helpdesk 

Rolling back to version 1.8.126 resolved the issue. The emails are now rendering correctly, as illustrated in the attached image. I've also included the email body from one of the affected messages, which was obtained from the 'Original message' -> 'Body' tab.

![image](https://github.com/freescout-helpdesk/freescout/assets/62724105/8a338e20-fa75-4af4-9f18-c13f58fa091d)

[body.txt](https://github.com/freescout-helpdesk/freescout/files/14908050/body.txt)

**Comment by freescout-helpdesk** [comment]
Fixed in the `master` branch and will be published in the next release.
