### ISSUE TITLE
[ISSUE : quoted messages] user replies with a quoted message it does not display in freescout

### ISSUE THREAD

**Issue by raramuridesign** [freescout-helpdesk/freescout#778]
When a user sends a reply back to freescout and has quoted a message from a previous email.

This message is not displayed in Freescout.

Could we understand why this is happening and can this be solved?

Matthew

**Comment by freescout-helpdesk** [comment]
Duplicates https://github.com/freescout-helpdesk/freescout/issues/765

**Comment by freescout-helpdesk** [comment]
Sorry

**Comment by raramuridesign** [comment]
The reply is happening from GMAIL.
I cannot provide full html, I hope the screenshot helps
You can see that the blockquote code was ignored.

![screenshot_blockquote](https://user-images.githubusercontent.com/902376/94903392-075de200-049a-11eb-9f3f-016a7cd7c213.png)

**Freescout view**

![screenshot_blockquote3](https://user-images.githubusercontent.com/902376/94903616-5c99f380-049a-11eb-8018-c50578f49b51.png)

![screenshot_blockquote2](https://user-images.githubusercontent.com/902376/94903464-25c3dd80-049a-11eb-8777-020a6afd9f74.png)

**Comment by freescout-helpdesk** [comment]
OK. Fixed in the `master` branch. Will be released in a few days.

**Comment by raramuridesign** [comment]
Thanks @freescout-helpdesk Thanks for the feedback. Really appreciate this.

**Comment by xavi-GH** [comment]
We have version "1.8.157" and we have the same problem.

- what i see in freescout mail panel:
---------------------
About the errors:

---------------------

- what i see in "Show Original"
[ preview tab ]
---------------------
About the errors:


> some quoted text

sometext
> other quoted text stuf..
---------------------

[ body tab ]
```
---------------------
About the errors:</div><div style="font-family: Arial, sans-serif; font-size: 14px;"><br></div><div class="protonmail_quote"><blockquote class="protonmail_quote" type="cite"><div style="width:100%!important; margin:0; padding:0" data-fs="
---------------------
```

**Comment by kuttnerd** [comment]
We have Version 1.8.195 and the Problem seems to still occur.
When a customer replies and the content includes a blockquote, the message gets cut off starting with the blockquote and the whole mail is just visible via the " show original message" Option. Meaning: we have to double check every message we get.
May it be possible to fix this?

**Comment by raramuridesign** [comment]
@kuttnerd It would be wise to show the source code with notes. It would be easier to troubleshoot - can you provide this ?

**Comment by kuttnerd** [comment]
@raramuridesign for sure. attached you can find a screenshot showing the cutoff in the message. 

What the customer did: responded to a mail and added a blockquote inside the message. 
What freescout did: just shows the message Part above the blockquote. The blockquote itself and the following part is hidden and just accessible via "Show Original Message".

<img width="1161" height="801" alt="Image" src="https://github.com/user-attachments/assets/c3fad8cf-d781-49fc-8578-66ccf40d3b1f" />

Can you reproduce that?

As workaround we added a button under the message to quickly double-check if any part of the message is missing.

**Comment by raramuridesign** [comment]
@kuttnerd If you click on the inhalt you will get the HTML - paste this here, and then I am sure @freescout-helpdesk  will take a look when you have posted this.

**Comment by kuttnerd** [comment]
@raramuridesign @freescout-helpdesk for sure, attached you can find two screenshots showing the source as preview and also as code/content. As you can see has the blockquote and the following content section been escaped in the code/content-view when a client uses blockquotes.

<img width="1150" height="777" alt="Image" src="https://github.com/user-attachments/assets/5b328b99-5281-498e-a715-3bf9321cddd0" />

<img width="1153" height="484" alt="Image" src="https://github.com/user-attachments/assets/73e31f5f-a944-45b5-bc58-e3bf5dfd5b80" />

the issue seems to exist for some time: https://github.com/freescout-help-desk/freescout/issues/4460

**Comment by raramuridesign** [comment]
@freescout-helpdesk Would you be able to look at this. This seems specific to Thunderbird.

**Comment by freescout-help** [comment]
HTML of the original email (not yet cropped) is needed.

And here is the list of reply separators FreeScout is using: https://github.com/freescout-help-desk/freescout/blob/dist/app/Misc/Mail.php#L60

**Comment by kuttnerd** [comment]
For sure @freescout-help , the HTML of the original in thunderbird with the following code copied out of thunderbird is

```Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 8bit

section before bockquote

> blockquote in mailclient thunderbird

section after bockquote

Am 13.11.2025 um 18:40 schrieb Daniel Kuttner:
> section before bockquote
>
>     blockquote in freescout
>
>
> section after bockquote
>
>
> --
```

<img width="1020" height="672" alt="Image" src="https://github.com/user-attachments/assets/579306bc-24d5-4981-ba3e-6faecc634447" />

**Comment by kuttnerd** [comment]
Do you need anything further @freescout-help ?

**Comment by sellth** [comment]
We also have this problem. Message looks like this:

<img width="860" height="164" alt="Image" src="https://github.com/user-attachments/assets/58449aff-9051-4f92-a25f-13f64802428f" />

and is parsed by Freescout as this:

<img width="897" height="236" alt="Image" src="https://github.com/user-attachments/assets/c205a784-3ea3-426e-98fb-5d2e3a2db6b5" />

I understand this might be by design to not show the "Reply quote" part of the message?
